### ISSUE TITLE
.tabs shouldnt contain content

### ISSUE THREAD

**Issue by Lampone** [vue-bulma/tabs#5]
http://bulma.io/documentation/components/tabs/

If content is inside in the .tabs class, it messes with styles. 
especially the size-modifier is-small is-medium and is-large.

**Comment by fundon** [comment]
Good catch! Thank you. Agree with you.

**Comment by fundon** [comment]
Landed in https://github.com/vue-bulma/tabs/releases/tag/v1.1.0.
