### ISSUE TITLE
Make content scrollable not tabs

### ISSUE THREAD

**Issue by MaestroJurko** [vue-bulma/tabs#6]
Is there an easy way to make content scrollable and tabs non scrollable/fixed? Now when scrolling, tabs are moving and I would like to have them static, so that only content inside is scrolling when using window scrollbar.

I tried using position fixed, but it did not solve the problem.

Any suggestions?

**Comment by MaestroJurko** [comment]
Any suggestions ????

**Comment by luventa** [comment]
Sorry for replying late.
I think there is a simple approach for this:
1. add a scoped css node.
2. set class, for example:
```
.vue-bulma-tabs > .tab-context { 
     height: 500px; 
     overflow-y: auto;
}
```
