### ISSUE TITLE
Watch tab change

### ISSUE THREAD

**Issue by MaestroJurko** [vue-bulma/tabs#7]
There has to be a way to watch which tab is selected.

**Comment by MaestroJurko** [comment]
Any suggestions ????

**Comment by MaestroJurko** [comment]
?????

Can you somehow add an event $emit for when a tab is selected?

**Comment by luventa** [comment]
Hi, I saw the [related pr](https://github.com/vue-bulma/tabs/pull/8) already raised by others.
